---
profiles:
  default:
    network: Custom
    private_key: ed25519-priv-0xd3b0422d8cd7d5360df08214ced597ec72ab91fee52b6cdfe5f5cddcb28ab9fa
    public_key: ed25519-pub-0x960f0e07ebd60946bf17d584dd411c9cb0b90b0028f6b645505aa2eca17c04c0
    account: 951cb360d9b1d4cb4834cf76e4fca0f63a85237874d8b2d45b3056439b91cbb7
    rest_url: "https://testnet.movementnetwork.xyz/v1"
