[package]
name = "velox"
version = "1.0.0"

[addresses]
velox = "0x44acd76127a76012da5efb314c9a47882017c12b924181379ff3b9d17b3cc8fb"

# [dev-addresses]
# velox = "0xbeef"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
