[package]
name = "velox"
version = "1.0.0"

[addresses]
velox = "0x94d017d8d944702a976af2844bdf3534b946e712cad286610aef5969568ba470"

# [dev-addresses]
# velox = "0xbeef"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
