[package]
name = "velox"
version = "1.0.0"

[addresses]
velox = "0x34ca2941f249796ce72ac2c0fc2ccb816936f53cd8aea7ef82bf621735634511"

# [dev-addresses]
# velox = "0xbeef"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
